"""human requests

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 11:36:30.056632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('form', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answers_path', sa.Text(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'submitted')", name='human_request_status_valid'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id')
    )
    op.drop_constraint('task_status_valid', 'tasks', type_='check')
    op.create_check_constraint('task_status_valid', 'tasks', "status IN ('proposed', 'approved', 'running', 'waiting_human', 'review', 'problem', 'done', 'cancelled')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human_requests')
    op.drop_constraint('task_status_valid', 'tasks', type_='check')
    op.create_check_constraint('task_status_valid', 'tasks', "status IN ('proposed', 'approved', 'running', 'review', 'problem', 'done', 'cancelled')")
    # ### end Alembic commands ###
