"""ai review

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-28 12:07:03.112791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_requests', sa.Column('answered_by', sa.String(length=8), server_default='human', nullable=False))
    op.add_column('projects', sa.Column('auto_ai_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_check_constraint('human_request_answered_by_valid', 'human_requests', "answered_by IN ('human', 'llm')")
    op.drop_constraint('step_kind_valid', 'steps', type_='check')
    op.create_check_constraint('step_kind_valid', 'steps', "kind IN ('plan', 'implement', 'run', 'review', 'analyze', 'verify', 'report')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auto_ai_review')
    op.drop_column('human_requests', 'answered_by')
    # ### end Alembic commands ###
    op.drop_constraint('step_kind_valid', 'steps', type_='check')
    op.create_check_constraint('step_kind_valid', 'steps', "kind IN ('plan', 'implement', 'run', 'analyze', 'verify', 'report')")
