"""task review_by

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-28 12:23:22.446758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('review_by', sa.String(length=8), nullable=True))
    op.create_check_constraint('task_review_by_valid', 'tasks', "review_by IS NULL OR review_by IN ('human', 'llm')")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('task_review_by_valid', 'tasks', type_='check')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'review_by')
    # ### end Alembic commands ###
